### PR TITLE
version for distribution

### PR DESCRIPTION
**Pull request by jasonkarns**
Would you consider including a pre-publish task to generate a browserify-standalone build of this?

We use browserify for our library as well, but we have need to use this in raw script-global form as well. Building the standalone version would be greatly appreciated.

### CODE REVIEW

**Comment by tmpfs** [comment]
Ok cool, I understand better now, I have no problem supporting this as it will likely have zero impact on the library but fulfil your use case.

Feel free to submit a pull request and I'll check it out, thanks for the input.

**Comment by jasonkarns** [comment]
Assuming the built file should be `dist/cookie.js`, and that the exported/global name of the module should be `Cookie` and that you'd like `dist/` to be ignored by git (since we only want it picked up by npm).

**Comment by tmpfs** [comment]
This has been merged and I have made a couple of small modifications, the `dist` directory was a red herring (legacy) and I have modified to build to the root directory as `cookie.js` and abbreviated the arguments.

Hope this helps. In the registry as `1.0.6`.

**Comment by jasonkarns** [comment]
I generally prefer the longform arguments for scripts as a form of self-documentation; prefering the short args for manual CLI invocations. But to each their own.

Thanks for accepting!

**Comment by tmpfs** [comment]
I hear you, I like the abbreviated versions in `npm` scripts for shorter column length ;) Ta!

**Pull request merged**
